# Server Configuration
server.port=8082
spring.application.name=equipment-service

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/equipmentlendingdatabase
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Secret Configuration
school.app.jwtSecret=SuperSecretKeyForSchoolLendingJWTs